/* The following code was generated by JFlex 1.7.0 */

/* archivo numero.jflex */
package ejemplo;


import java.util.ArrayList;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/ejemplo/numero.jflex</tt>
 */
class Numero implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\37\1\51\1\0\1\40\23\0\1\36\3\0\1\26"+
    "\2\0\1\30\1\31\1\24\1\22\1\0\1\23\1\2\1\25\12\1"+
    "\1\33\1\0\1\32\1\27\1\32\2\0\1\42\2\4\1\42\11\4"+
    "\2\42\2\4\1\42\10\4\1\34\1\0\1\35\1\26\2\0\1\11"+
    "\1\21\1\20\1\10\1\6\1\13\1\50\1\4\1\44\2\4\1\14"+
    "\1\46\1\16\1\12\1\45\1\4\1\7\1\15\1\17\1\47\1\5"+
    "\1\4\1\43\2\4\1\0\1\41\10\0\1\51\u05da\0\12\3\206\0"+
    "\12\3\306\0\12\3\u019c\0\12\3\166\0\12\3\166\0\12\3\166\0"+
    "\12\3\166\0\12\3\166\0\12\3\166\0\12\3\166\0\12\3\166\0"+
    "\12\3\166\0\12\3\140\0\12\3\166\0\12\3\106\0\12\3\u0116\0"+
    "\12\3\106\0\12\3\u0746\0\12\3\46\0\12\3\u012c\0\12\3\200\0"+
    "\12\3\246\0\12\3\6\0\12\3\266\0\12\3\126\0\12\3\206\0"+
    "\12\3\6\0\12\3\u03ce\0\1\51\1\51\u85f6\0\12\3\u02a6\0\12\3"+
    "\46\0\12\3\306\0\12\3\26\0\12\3\126\0\12\3\u0196\0\12\3"+
    "\u5316\0\12\3\u0586\0\12\3\u0bbc\0\12\3\200\0\12\3\74\0\12\3"+
    "\220\0\12\3\u0116\0\12\3\u0156\0\12\3\166\0\12\3\u0176\0\12\3"+
    "\146\0\12\3\146\0\12\3\u01a6\0\12\3\u0366\0\12\3\u4e06\0\12\3"+
    "\346\0\12\3\u6c74\0\62\3\u1150\0\12\3\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u16b5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\7\3\5\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\2\1\2\14\2\3\1\0"+
    "\10\3\1\15\1\16\1\17\1\20\3\3\1\21\17\3"+
    "\1\22\14\3\1\23\1\3\1\24\21\3\1\25\1\26"+
    "\1\3\1\27\2\3\1\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\52\0\u024c"+
    "\0\52\0\52\0\52\0\52\0\52\0\52\0\u024c\0\u0276"+
    "\0\52\0\176\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348\0\u0372"+
    "\0\u039c\0\u03c6\0\u03f0\0\u041a\0\u0444\0\52\0\52\0\52"+
    "\0\52\0\u046e\0\u0498\0\u04c2\0\52\0\u04ec\0\u0516\0\u0540"+
    "\0\u056a\0\u0594\0\u05be\0\u05e8\0\u0612\0\u063c\0\u0666\0\u0690"+
    "\0\u06ba\0\u06e4\0\u070e\0\u0738\0\176\0\u0762\0\u078c\0\u07b6"+
    "\0\u07e0\0\u080a\0\u0834\0\u085e\0\u0888\0\u08b2\0\u08dc\0\u0906"+
    "\0\u0930\0\176\0\u095a\0\176\0\u0984\0\u09ae\0\u09d8\0\u0a02"+
    "\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4\0\u0afe\0\u0b28\0\u0b52"+
    "\0\u0b7c\0\u0ba6\0\u0bd0\0\u0bfa\0\u0c24\0\176\0\176\0\u0c4e"+
    "\0\176\0\u0c78\0\u0ca2\0\176";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\2\1\4\1\5\1\6\1\7\3\4"+
    "\1\10\4\4\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\2\1\30\1\31\1\32\2\4\1\33\1\34"+
    "\2\4\54\0\1\3\1\35\53\0\16\4\20\0\7\4"+
    "\5\0\2\4\1\36\13\4\20\0\7\4\5\0\12\4"+
    "\1\37\3\4\20\0\1\4\1\40\5\4\5\0\2\4"+
    "\1\41\13\4\20\0\7\4\5\0\5\4\1\42\10\4"+
    "\20\0\7\4\5\0\5\4\1\43\2\4\1\44\5\4"+
    "\20\0\7\4\5\0\6\4\1\45\7\4\20\0\7\4"+
    "\23\0\1\46\52\0\1\47\53\0\1\50\50\0\2\51"+
    "\53\0\1\23\61\0\1\2\16\0\3\4\1\52\12\4"+
    "\20\0\5\4\1\53\1\4\5\0\2\4\1\54\13\4"+
    "\20\0\7\4\2\0\1\55\1\0\1\55\52\0\3\4"+
    "\1\56\12\4\20\0\7\4\5\0\13\4\1\57\2\4"+
    "\20\0\7\4\5\0\13\4\1\60\2\4\20\0\7\4"+
    "\5\0\5\4\1\61\10\4\20\0\7\4\5\0\10\4"+
    "\1\62\5\4\20\0\7\4\5\0\4\4\1\63\11\4"+
    "\20\0\7\4\5\0\5\4\1\64\10\4\20\0\7\4"+
    "\5\0\6\4\1\65\7\4\20\0\7\4\5\0\6\4"+
    "\1\66\7\4\20\0\2\4\1\67\4\4\5\0\15\4"+
    "\1\70\20\0\7\4\5\0\13\4\1\71\2\4\20\0"+
    "\7\4\5\0\4\4\1\72\11\4\20\0\7\4\5\0"+
    "\2\4\1\73\13\4\20\0\7\4\5\0\16\4\20\0"+
    "\2\4\1\74\4\4\5\0\10\4\1\75\5\4\20\0"+
    "\7\4\5\0\11\4\1\76\4\4\20\0\7\4\5\0"+
    "\2\4\1\77\13\4\20\0\7\4\5\0\11\4\1\100"+
    "\4\4\20\0\7\4\5\0\10\4\1\101\5\4\20\0"+
    "\7\4\5\0\13\4\1\102\2\4\20\0\3\4\1\103"+
    "\3\4\5\0\1\4\1\104\14\4\20\0\7\4\5\0"+
    "\10\4\1\105\5\4\20\0\7\4\5\0\6\4\1\106"+
    "\7\4\20\0\7\4\5\0\5\4\1\107\10\4\20\0"+
    "\7\4\5\0\3\4\1\110\12\4\20\0\7\4\5\0"+
    "\2\4\1\111\13\4\20\0\7\4\5\0\6\4\1\112"+
    "\7\4\20\0\7\4\5\0\12\4\1\113\3\4\20\0"+
    "\7\4\5\0\2\4\1\114\13\4\20\0\7\4\5\0"+
    "\2\4\1\115\13\4\20\0\7\4\5\0\2\4\1\116"+
    "\13\4\20\0\7\4\5\0\16\4\20\0\2\4\1\117"+
    "\4\4\5\0\5\4\1\120\10\4\20\0\7\4\5\0"+
    "\16\4\20\0\2\4\1\121\4\4\5\0\4\4\1\122"+
    "\11\4\20\0\7\4\5\0\4\4\1\123\11\4\20\0"+
    "\7\4\5\0\6\4\1\75\7\4\20\0\7\4\5\0"+
    "\12\4\1\124\3\4\20\0\7\4\5\0\5\4\1\75"+
    "\10\4\20\0\7\4\5\0\5\4\1\125\10\4\20\0"+
    "\7\4\5\0\16\4\20\0\6\4\1\126\5\0\2\4"+
    "\1\127\13\4\20\0\7\4\5\0\4\4\1\130\11\4"+
    "\20\0\7\4\5\0\14\4\1\130\1\4\20\0\7\4"+
    "\5\0\6\4\1\131\7\4\20\0\7\4\5\0\2\4"+
    "\1\132\13\4\20\0\7\4\5\0\4\4\1\133\11\4"+
    "\20\0\7\4\5\0\12\4\1\110\3\4\20\0\7\4"+
    "\5\0\16\4\20\0\2\4\1\120\4\4\5\0\4\4"+
    "\1\134\11\4\20\0\7\4\5\0\5\4\2\135\7\4"+
    "\20\0\7\4\5\0\11\4\1\136\4\4\20\0\7\4"+
    "\5\0\3\4\1\76\12\4\20\0\7\4\5\0\2\4"+
    "\1\137\13\4\20\0\7\4\5\0\5\4\1\140\10\4"+
    "\20\0\7\4\5\0\11\4\1\141\4\4\20\0\7\4"+
    "\5\0\4\4\1\142\11\4\20\0\7\4\5\0\2\4"+
    "\1\143\13\4\20\0\7\4\5\0\11\4\1\144\4\4"+
    "\20\0\7\4\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3276];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\14\1\1\11\1\1\6\11\2\1\1\11"+
    "\3\1\1\0\10\1\4\11\3\1\1\11\67\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  public boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public ArrayList<Token> tokens;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Numero(java.io.Reader in) {
      this.tokens = new ArrayList<>();
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 384) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            } 
            // fall through
          case 25: break;
          case 2: 
            { System.out.println("Encontre un Entero: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("entero",yytext()));
            } 
            // fall through
          case 26: break;
          case 3: 
            { System.out.println("Encontre una Cadena: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("cadena",yytext()));
            } 
            // fall through
          case 27: break;
          case 4: 
            { System.out.println("Encontre un Simbolo aritmetico: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("simaritmetico",yytext()));
            } 
            // fall through
          case 28: break;
          case 5: 
            { System.out.println("Encontre una Asignacion: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("asignacion",yytext()));
            } 
            // fall through
          case 29: break;
          case 6: 
            { System.out.println("Encontre una Abertura de parentesis: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("openpar",yytext()));
            } 
            // fall through
          case 30: break;
          case 7: 
            { System.out.println("Encontre un Cierre de parentesis: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("closepar",yytext()));
            } 
            // fall through
          case 31: break;
          case 8: 
            { System.out.println("Encontre una Condicion: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("condicion",yytext()));
            } 
            // fall through
          case 32: break;
          case 9: 
            { System.out.println("Encontre Dos puntos: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("dospuntos",yytext()));
            } 
            // fall through
          case 33: break;
          case 10: 
            { System.out.println("Encontre una apertura de corchetes: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("opencorch",yytext()));
            } 
            // fall through
          case 34: break;
          case 11: 
            { System.out.println("Encontre un cierre de corchetes: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("closecorch",yytext()));
            } 
            // fall through
          case 35: break;
          case 12: 
            { System.out.println("Encontre un operador logico: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("operadorlogico",yytext()));
            } 
            // fall through
          case 36: break;
          case 13: 
            { System.out.println("Encontre un Incremento: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("incremento",yytext()));
            } 
            // fall through
          case 37: break;
          case 14: 
            { System.out.println("Encontre un Decremento: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("decremento",yytext()));
            } 
            // fall through
          case 38: break;
          case 15: 
            { System.out.println("Encontre un Cierre de comentario: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("closecom",yytext()));
            } 
            // fall through
          case 39: break;
          case 16: 
            { System.out.println("Encontre Apertura de comentario: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("opencom",yytext()));
            } 
            // fall through
          case 40: break;
          case 17: 
            { System.out.println("Encontre un Real: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("real",yytext()));
            } 
            // fall through
          case 41: break;
          case 18: 
            { System.out.println("Encontre un tipo de variable: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("TipoVariable",yytext()));
            } 
            // fall through
          case 42: break;
          case 19: 
            { System.out.println("Encontre un Booleano: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("booleano",yytext()));
            } 
            // fall through
          case 43: break;
          case 20: 
            { System.out.println("Encontre un declaracion de clase: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("class",yytext()));
            } 
            // fall through
          case 44: break;
          case 21: 
            { System.out.println("Encontre una declaracion de metodos: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("methods",yytext()));
            } 
            // fall through
          case 45: break;
          case 22: 
            { System.out.println("Encontre un extends: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("extends",yytext()));
            } 
            // fall through
          case 46: break;
          case 23: 
            { System.out.println("Encontre un tipo de acceso: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("tipoacceso",yytext()));
            } 
            // fall through
          case 47: break;
          case 24: 
            { System.out.println("Encontre una declaracion de propiedades: " + yytext());
    System.out.println("Encontrado en :" + yyline + "-" + yycolumn);
    tokens.add(new Token("props",yytext()));
            } 
            // fall through
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
